Repository niirmaaltwaatii/PyScripts, pull requests merged in 2023-10, with the labels that each got.

#4 Random Password Generater
  random password generator/README.md
  random password generator/requirements.txt
  random password generator/rpg.py
Labels: enhancement, hacktoberfest-accepted

#5 File Organizer Script
  file organizer/README.md
  file organizer/fileorg.py
  file organizer/requirements.txt
Labels: enhancement, hacktoberfest-accepted

#6 Dice Roller
  dice roller/README.md
  dice roller/dice.py
Labels: enhancement, hacktoberfest-accepted

#7 QR Code Generator
  qr code generator/README.md
  qr code generator/qrgen.py
  qr code generator/requirements.txt
Labels: enhancement, hacktoberfest-accepted

#8 Added mouse moving scirpt
  mouse mover/README.md
  mouse mover/mouse_mover.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted

#10 ASCII ART
  ASCII ART/README.md
  ASCII ART/app.py
  ASCII ART/convert_image.py
  ASCII ART/templates/index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#11 Fixed spelling issues in readme
  ASCII ART/README.md
  dice roller/README.md
  file organizer/README.md
  qr code generator/README.md
  random password generator/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#12 Hangman
  Hangman/hangman.py
  Hangman/readme.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#13 Word
  word/readme.md
  word/word.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
